### PR TITLE
Remove ovirt_engine_answer_file_type

### PR DESCRIPTION
**Pull request by vkondula**
Every occurrence of ovirt_engine_answer_file_type
 variable is replaced by ovirt_engine_version.
It's possible to specify own answer file for
 engine-setup.

resolves: #29

### CODE REVIEW

**Comment by vkondula** [comment]
I will rebase this after #81 is merged.

**Comment by vkondula** [comment]
rebased, please check

**Comment by lukas-bednar** [comment]
this change breaks interface (is not backward compatible), I have to include it in different release.

**Comment by vkondula** [comment]
@lukas-bednar  technically you are right. But if someone sets the "ovirt_engine_answer_file_type" it's simply ignored.
And since answers files are not backward compatible, there were no other use-cases than:
- version 3.6 -> 3.6 ans.file
- version 4.0 -> 4.0 ans.file
- version 4.1 -> 4.1 ans.file (symlink to 4.0 ans.file)
which is preserved.

**Comment by lukas-bednar** [comment]
@vkondula ok I will consider that. thanks!

**Pull request merged**
